FROM ruby:2.3.1
RUN apt-get update -qq && apt-get install -y build-essential make cmake autoconf automake libcurl3 zlib1g-dev libqt4-dev bison libpq-dev imagemagick libmagickwand-dev libkrb5-dev libicu-dev libssl-dev libyaml-dev zlib1g-dev libxml2-dev libxslt1-dev libcurl4-openssl-dev libqtwebkit-dev bison libssl-dev  libc6-dev
ENV RAILS_ROOT /contactrocket
ENV RAILS_ENV production
RUN mkdir -p $RAILS_ROOT
WORKDIR /contactrocket
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock
RUN bundle install
COPY . .
CMD ["config/containers/app_cmd.sh"]

