# Load DSL and Setup Up Stages
require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/bundler'
require 'capistrano/sidekiq'
require 'capistrano/sidekiq/monit'
Dir.glob('lib/capistrano/tasks/*.cap').each { |r| import r }
