

guard :bundler do
  require 'guard/bundler'
  require 'guard/bundler/verify'
  helper = Guard::Bundler::Verify.new
  files = ['Gemfile']
  files += Dir['*.gemspec'] if files.any? { |f| helper.uses_gemspec?(f) }
  files.each { |file| watch(helper.real_path(file)) }
end


guard 'sidekiq', :cli => '-C config/sidekiq.yml -L log/sidekiq.log -P tmp/pids/sidekiq.pid -e development' do
  watch(%r{^workers/(.+)\.rb$})
  watch(%r{^models/(.+)\.rb$})
end


guard :rspec, cmd: "bundle exec rspec"  do
  require "guard/rspec/dsl"
  dsl = Guard::RSpec::Dsl.new(self)

  # RSpec files
  rspec = dsl.rspec
  watch(rspec.spec_support) { rspec.spec_dir }
  watch(rspec.spec_files)

  # Ruby files
  ruby = dsl.ruby
  dsl.watch_spec_files_for(ruby.lib_files)

end




