default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: contactrocket
  schema_search_path: public,shared_extensions

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  port: 5432
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  database: <%= ENV['RDS_DB_NAME'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  schema_search_path: public,shared_extensions

