version: '2'

services:

  rabbitmq:
    image: tutum/rabbitmq
    dns: ["8.8.8.8"]
    environment:
      - "RABBITMQ_PASS=password"
  
  # Start transformation worker
  strokewidthtransform:
    image: tleyden5iwx/open-ocr-preprocessor
    volumes: 
      - ./scripts/:/opt/open-ocr/
    dns: ["8.8.8.8"]
    links:
      - rabbitmq
    command: "/opt/open-ocr/open-ocr-preprocessor -amqp_uri amqp://admin:password@rabbitmq/ -preprocessor stroke-width-transform"
  
  # Start OCR worker
  openocrworker:
    image: tleyden5iwx/open-ocr
    volumes: 
      - ./scripts/:/opt/open-ocr/
    dns: ["8.8.8.8"]
    links:
      - rabbitmq
    command: "/opt/open-ocr/open-ocr-worker -amqp_uri amqp://admin:password@rabbitmq/"
  
  # Start http server
  openocr:
    image: tleyden5iwx/open-ocr
    dns: ["8.8.8.8"]
    volumes: 
      - ./scripts/:/opt/open-ocr/
    links:
      - rabbitmq
    ports:
      - "9292:9292"
    command: "/opt/open-ocr/open-ocr-httpd -amqp_uri amqp://admin:password@rabbitmq/ -http_port 9292"


  ui:  
    restart: on-failure
    image: pgbi/kong-dashboard
    ports:
      - "8081:8080"



volumes:
  redis:
  postgres:
  elasticsearch:
  statsd:
