:concurrency: 10
:timeout: 60

development:
  :concurrency: 10
  :queues:
    - [default,4]
    - [crawler,2]
    - searchkick
    - text
test:
  :concurrency: 10
  :queues:
    - [default,4]
    - [crawler,2]
    - searchkick
    - text
production:
  :concurrency: 10
  :queues:
    - [default,4]
    - [crawler,2]
    - searchkick
    - validation
    - text