---

development: &default

test:

staging:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  secret_token: <%= ENV['SECRET_TOKEN'] %>

production:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  secret_token: <%= ENV['SECRET_TOKEN'] %>
